name: technical_exercise
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rxdart: ^0.27.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.2
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
